test('empty test', () => {
    expect(true).toBe(false);
});

const shrinkwrapStub = 
{
    "name": "package-name",
    "version": "1.2832.0",
    "dependencies": {
      "package1": {
        "version": "1.1.0",
        "from": "package1@>=1.0.0 <2.0.0",
        "resolved": "http://npm.f4tech.com/artifactory/api/npm/rally-npm/package1/-/package1-1.1.0.tgz"
      },
      "package2": {
        "version": "1.3.3",
        "from": "package2@1.3.3",
        "resolved": "http://npm.f4tech.com/artifactory/api/npm/rally-npm/package2/-/package2-1.3.3.tgz"
      },
      "package3": {
        "version": "5.1.1",
        "from": "package3@>=5.0.0 <6.0.0",
        "resolved": "http://npm.f4tech.com/artifactory/api/npm/rally-npm/package3/-/package3-5.1.1.tgz"
      },
      "package4": {
        "version": "2.0.2",
        "from": "package4@>=2.0.0 <3.0.0",
        "resolved": "http://npm.f4tech.com/artifactory/api/npm/rally-npm/package4/-/package4-2.0.2.tgz",
        "dependencies": {
          "package5": {
            "version": "4.0.13",
            "from": "package5@>=4.0.3 <5.0.0",
            "resolved": "http://npm.f4tech.com/artifactory/api/npm/rally-npm/package5/-/package5-4.0.13.tgz"
          }
        }
      }
    }
}

const lockfileStub = 
  `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1
  
  abab@^1.0.3:
    version "1.0.3"
    resolved "https://registry.yarnpkg.com/abab/-/abab-1.0.3.tgz#b81de5f7274ec4e756d797cd834f303642724e5d"
  
  abbrev@1:
    version "1.1.0"
    resolved "https://registry.yarnpkg.com/abbrev/-/abbrev-1.1.0.tgz#d0554c2256636e2f56e7c2e5ad183f859428d81f"
  
  acorn-globals@^3.1.0:
    version "3.1.0"
    resolved "https://registry.yarnpkg.com/acorn-globals/-/acorn-globals-3.1.0.tgz#fd8270f71fbb4996b004fa880ee5d46573a731bf"
    dependencies:
      acorn "^4.0.4"`